python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 run_layer_stats.py 
python3 run_layer_stats.py 
python3 run_layer_stats.py 
python3 run_layer_stats.py 
python3 run_layer_stats.py 
python3 run_layer_stats.py 
python3 run_layer_stats.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
gst
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
which python
python run_layer_stats.py 
python3 run_layer_stats.py 
python3 run_layer_stats.py 
python3 run_layer_stats.py 
python3 run_layer_stats.py 
python3 run_layer_stats.py 
python3 run_layer_stats.py 
clear
clear
python3 run_layer_stats.py 
python3 run_layer_stats.py 
python3 run_layer_stats.py 
python3 run_layer_stats.py 
python3 temp.py
python3 temp.py
python3 temp.py
python3 temp.py
python3 temp.py
python3 temp.py
python3 temp.py
python3 temp.py
python3 temp.py
python3 temp.py
python3 temp.py
python3 temp.py
python3 temp.py
python3 temp.py
python3 temp.py
python3 temp.py
python3 temp.py
clear
python3 temp.py
python3 temp.py
python3 temp.py
python3 temp.py
python3 temp.py
python3 temp.py
python3 temp.py
python3 temp.py
python3 temp.py
python3 temp.py
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py 
python3 genetic_algo_timeloop.py
python3 genetic_algo_timeloop.py
python3 genetic_algo_timeloop.py
python3 genetic_algo_timeloop.py
python3 genetic_algo_timeloop.py
